./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
cd ..
ls
cd ns3-rdma-main/
ls
quit
exit
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
ls
cd ns3-rdma-main/
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
quit
exit
ls
cd ns3-rdma-main/
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
exit
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
ls
cd ns3-rdma-main/
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
exit
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
ls
cd ns3-rdma-main/
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
cd ..
exit
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
ls
cd ns3-rdma-main/
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1 --command-template="gdb --args %s <args>"
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run scratch/network-load-balance --command-template="gdb --args %s mix/output/1/config.txt"
export LD_LIBRARY_PATH=$PWD/build:$LD_LIBRARY_PATH
gdb ./build/scratch/network-load-balance
./waf --run scratch/network-load-balance --command-template="gdb --args %s mix/output/1/config.txt"
./waf --run scratch/network-load-balance --command-template="gdb --args %s mix/output/1/config.txt"
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run scratch/network-load-balance --command-template="gdb --args %s mix/output/1/config.txt"
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
quit
exit
exit
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
ls
cd NS3-MP-RDMA/
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
cd ..
cd NS3-RDMA-MIN
cd NS3-RDMA-MAIN
ls
cd ns3-rdma-main/
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
./waf --run 'scratch/network-load-balance mix/output/1/config.txt' > mix/output/1/config.log 2>&1
quit
exit
exit
