FROM ubuntu:18.04

# 安装 gcc-5/g++-5
RUN apt update && apt install -y software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt update && apt install -y gcc-5 g++-5 python python3 git make

# 设置工作目录
WORKDIR /root

# （可选）把 NS3-MP-RDMA 复制到容器里
# COPY NS3-MP-RDMA /ns3d/NS3-MP-RDMA
